#ifndef METLIBS_COSERVER_VERSION_H
#define METLIBS_COSERVER_VERSION_H

#define METLIBS_COSERVER_VERSION_MAJOR 2
#define METLIBS_COSERVER_VERSION_MINOR 0
#define METLIBS_COSERVER_VERSION_PATCH 3

#define METLIBS_COSERVER_VERSION_INT(major,minor,patch) \
    (1000000*major + 1000*minor + patch)
#define METLIBS_COSERVER_VERSION_CURRENT_INT \
    MIFI_VERSION_INT(MIFI_VERSION_MAJOR, MIFI_VERSION_MINOR, MIFI_VERSION_PATCH)

#endif // METLIBS_COSERVER_VERSION_H
