#ifndef METLIBS_COSERVER_VERSION_H
#define METLIBS_COSERVER_VERSION_H

#define METLIBS_COSERVER_VERSION_MAJOR 2
#define METLIBS_COSERVER_VERSION_MINOR 3
#define METLIBS_COSERVER_VERSION_PATCH 0

#define METLIBS_COSERVER_VERSION_INT(major,minor,patch) \
    (1000000*major + 1000*minor + patch)
#define METLIBS_COSERVER_VERSION_CURRENT_INT \
    METLIBS_COSERVER_VERSION_INT(METLIBS_COSERVER_VERSION_MAJOR, METLIBS_COSERVER_VERSION_MINOR, METLIBS_COSERVER_VERSION_PATCH)

#endif // METLIBS_COSERVER_VERSION_H
